# Generated by Django 6.0.2 on 2026-03-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
